name: Form resume artefacts

on: push
# push:
#   branches:
#     - get-resume-at-par
      
jobs:
  Forms-Resume-To-Share:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install the dependencies
        run: |
          npm install https://github.com/floatdrop/pinkie-promise.git
          npm install
          npm install hackmyresume -g
          npm install escape-string-regexp -g
      - name: Validates the resume data
        run: |
          node node_modules/resume-cli/build/main.js validate
          hackmyresume validate resume.json
      - name: Generates the static resume bundles for web and pdf
        run: node helper_scripts/generate_for_themes.js ./
      - name: Analyze resume using HackMyResume
        run: hackmyresume analyze resume.json
      - name: Upload artefacts from HackMyResume
        run: |
          mkdir hackmyresume
          hackmyresume build resume.json hackmyresume/resume.doc -t node_modules/jsonresume-theme-short
          curl --upload-file ./hackmyresume/resume.doc https://transfer.sh/amir_resume.doc
      - name: Get the landing page setup in place
        run: cp -a ./landing_page/. ./public/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.